# -*- coding: utf-8 -*-
"""calculadora_Ingrid_Garcia-Exercicio2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wzd9uPeaQ1vg4iQz8KjP9V1IIpsxD0vj

###**Calculadora Básica**
"""

# Criar funções específicas para cada operação, seguindo o princípio da responsabilidade única.
def somar(a, b):
    """Retorna a soma de dois números."""
    return a + b

def subtrair(a, b):
    """Retorna a diferença entre dois números."""
    return a - b

def multiplicar(a, b):
    """Retorna o produto de dois números."""
    return a * b

def dividir(a, b):
    """Retorna a divisão, tratando o erro matemático de divisão por zero."""
    if b == 0:
        return "Erro: Não é possível dividir por zero!"
    return a / b

# --- FLUXO PRINCIPAL ---
# Variável de controle de repetição

continuar = 's'
while continuar == 's':
  # Bloco 'try' para capturar erros de entrada (Resiliência do código)
    try:
        # Entrada de dados convertida para ponto flutuante (float)
        num1 = float(input("Digite o primeiro número: "))
        num2 = float(input("Digite o segundo número: "))

        print("\nEscolha uma opção para calcular:")
        print("1 - Soma | 2 - Subtração | 3 - Multiplicação | 4 - Divisão")

        opcao = input("\nDigite o número da opção desejada (1/2/3/4): ")

        if opcao == '1':
            resultado = num1 + num2
            print(f"Resultado da Soma: {resultado}")
        elif opcao == '2':
            resultado = num1 - num2
            print(f"Resultado da Subtração: {resultado}")
        elif opcao == '3':
            resultado = num1 * num2
            print(f"Resultado da Multiplicação: {resultado}")
        elif opcao == '4':
            if num2 != 0:
                resultado = num1 / num2
                print(f"Resultado da Divisão: {resultado}")
            else:
                print("Erro: Não é possível dividir por zero!")
        else:
            print("Opção inválida!")

  # O bloco 'except' é executado se o float() falhar (ex: se o usuário digitar uma letra)
    except ValueError:
      print("Erro: Entrada inválida! Por favor, utilize apenas números.")

    # A linha abaixo foi indentada para corrigir o IndentationError
    continuar = input("\nDeseja realizar um novo cálculo? Digite: s (para sim) ou n (para não): ")

print("\nCalculadora encerrada!")

