# -*- coding: utf-8 -*-
"""calculadora_Ingrid_Garcia-Exercicio2.2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_j1ut6qbORycb0KU5tnHpZv5kjVnBP-u

###**Calculadora Básica**
"""

# Funções específicas para cada operação, seguindo o princípio da responsabilidade única.
def somar(a, b):
    return a + b

def subtrair(a, b):
    return a - b

def multiplicar(a, b):
    return a * b

def dividir(a, b):
    if b == 0:
        return "Erro: Não é possível dividir por zero!"
    return a / b

# --- FLUXO PRINCIPAL ---
# Variável de controle de repetição

continuar = 's'
while continuar == 's':
  # Bloco 'try' para capturar erros de entrada (Resiliência do código)
    try:

        num1 = float(input("Digite o primeiro número: "))
        num2 = float(input("Digite o segundo número: "))

        print("\nEscolha uma opção para calcular:")
        print("1 - Soma | 2 - Subtração | 3 - Multiplicação | 4 - Divisão")

        opcao = input("\nDigite o número da opção desejada (1/2/3/4): ")

        if opcao == '1':
            resultado = num1 + num2
            print(f"Resultado da Soma: {resultado}")
        elif opcao == '2':
            resultado = num1 - num2
            print(f"Resultado da Subtração: {resultado}")
        elif opcao == '3':
            resultado = num1 * num2
            print(f"Resultado da Multiplicação: {resultado}")
        elif opcao == '4':
            if num2 != 0:
                resultado = num1 / num2
                print(f"Resultado da Divisão: {resultado}")
            else:
                print("Erro: Não é possível dividir por zero!")
        else:
            print("Opção inválida!")

  # O bloco 'except' é executado se o float() falhar (ex: se o usuário digitar uma letra)
    except ValueError:
      print("Erro: Entrada inválida! Por favor, utilize apenas números.")

    continuar = input("\nDeseja realizar um novo cálculo? Digite: s (para sim) ou n (para não): ")

print("\nCalculadora encerrada!")

